#!/usr/bin/env python
# ./anim <effect> <path>
# renders starting from the first frame
#
# Known issues:
# Blender's -s and -e flags that set start and end frame seem
# broken atm.
import sys
from subprocess import Popen

import init

sp = Popen(["/bin/bash", "-i", "-c", "blender -b simulator.blend -P sim.py -a"])
sp.communicate()
