#!/usr/bin/env python
# ./anim <effect> <path>
# renders starting from the first frame
import os

import utils

if __name__ == '__main__':
    p = utils.effect_parser()
    p.add_argument('--length', help="Animation length in seconds", type=float)

    args = p.parse_args()

    length = args.length or ''
    os.environ['length'] = str(length)

    utils.export(args.effect, args.output, length, sensors=args.sensors)
    utils.render_animation(args.effect, args.output, length)
