#!/usr/bin/env python
# ./anim <effect> <path>
# renders starting from the first frame
import os
from subprocess import Popen

import init

p = init.parser()
p.add_argument('--length', help="Animation length in seconds", type=int)

args = p.parse_args()

os.environ['length'] = str(args.length or '')

init.execute(args)

sp = Popen(["/bin/bash", "-i", "-c", "blender -b blender/simulator.blend" + \
    " -P blender/sim.py -a"])
sp.communicate()
