#!/usr/bin/env python
# ./frame <effect> <path> <frame>
from subprocess import Popen

import init

p = init.parser()
p.add_argument('frame')
args = p.parse_args()
init.execute(args)

sp = Popen(["/bin/bash", "-i", "-c",
    "blender -b simulator.blend -P sim.py -f " + args.frame])
sp.communicate()
