#!/usr/bin/env python
# ./playlist <playlist> <path>
import os
import sys
import json

import utils

sys.path.append(os.path.join(os.getcwd(), '..'))

from generators import playlists


def seek(data, name):
    for d in data:
        if d.get('name') == name:
            return d.get('playlist')


def main():
    p = utils.parser()
    p.add_argument('playlist', help='name of the playlist to render')
    p.add_argument('output', help='output path')

    data = playlists.load(os.path.join(os.getcwd(), '..', 'src', 'playlists'))

    if data:
        args = p.parse_args()

        playlist = seek(data, name=args.playlist)

        fps = 0
        geometry = None
        length = 0
        frames = []
        for effect in playlist:
            l = float(effect['length']) / 1000.0
            utils.export(effect['name'], args.output, l)
            length += l

            with open(os.path.join('exports', effect['name'] + '.json'),
                    'r') as f:
                d = json.load(f)
                frames.extend(d['frames'][:int(l * d['fps'])])
                fps = d['fps']
                geometry = d['geometry']

        with open(os.path.join('exports', 'playlist.json'), 'w') as f:
            json.dump({
                    'fps': fps,
                    'geometry': geometry,
                    'frames': frames,
                },
                f
            )

        utils.render_animation('playlist', args.output, length)


if __name__ == '__main__':
    main()
