/* -*- mode: c; c-file-style: "linux" -*-
 *  vi: set shiftwidth=8 tabstop=8 noexpandtab:
 *
 *  Copyright 2012 Elovalo project group 
 *  
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <stdint.h>
#include "../../pgmspace.h"

/* Pre-calculated Weber–Fechner table generated by helpers/WeberFechner.hs */
const uint16_t weber_fechner_table[] PROGMEM = {0,0,0,0,0,0,0,0,0,0,0,0,0,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,12,12,12,12,12,12,12,12,12,12,13,13,13,13,13,13,13,13,14,14,14,14,14,14,15,15,15,15,15,16,16,16,16,17,17,17,17,18,18,18,18,19,19,19,20,20,21,21,21,22,22,23,23,23,24,24,25,26,26,27,27,28,28,29,30,30,31,32,33,33,34,35,36,37,38,39,40,41,42,43,44,45,46,48,49,50,52,53,54,56,57,59,61,62,64,66,68,70,72,74,76,78,81,83,85,88,91,93,96,99,102,105,108,112,115,118,122,126,130,134,138,142,147,151,156,161,166,171,176,182,188,193,200,206,212,219,226,233,241,248,256,265,273,282,291,300,310,320,330,341,352,363,375,387,400,412,426,440,454,469,484,500,516,533,550,568,587,606,625,646,667,689,711,735,759,784,809,836,863,891,921,951,982,1014,1048,1082,1118,1154,1192,1232,1272,1314,1357,1402,1448,1496,1545,1596,1649,1703,1759,1817,1877,1939,2003,2069,2137,2208,2281,2356,2434,2514,2597,2683,2772,2863,2958,3056,3157,3261,3369,3480,3595,3714,3837,3964,4095};

uint16_t weber_fechner(uint8_t i) {
	return pgm_get(weber_fechner_table[i],word);
}
