/* -*- mode: c; c-file-style: "linux" -*-
 *  vi: set shiftwidth=8 tabstop=8 noexpandtab:
 *
 *  Copyright 2012 Elovalo project group 
 *  
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <stdint.h>
#include "../../pgmspace.h"

/* Pre-calculated Weber–Fechner table generated by helpers/WeberFechner.hs */
const uint16_t weber_fechner_table[] PROGMEM = {1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,5,5,5,5,5,5,6,6,6,6,6,7,7,7,7,8,8,8,8,9,9,9,9,10,10,10,11,11,12,12,12,13,13,14,14,15,15,15,16,17,17,18,18,19,19,20,21,21,22,23,24,24,25,26,27,28,29,30,31,32,33,34,35,36,37,39,40,41,43,44,45,47,48,50,52,53,55,57,59,61,63,65,67,69,72,74,77,79,82,84,87,90,93,96,99,103,106,110,113,117,121,125,129,133,138,142,147,152,157,162,168,173,179,185,191,197,204,210,217,225,232,240,248,256,264,273,282,292,301,311,322,332,343,355,366,379,391,404,417,431,446,460,476,491,508,525,542,560,579,598,618,638,659,681,704,727,751,776,802,828,856,884,913,944,975,1007,1041,1075,1111,1148,1186,1225,1266,1308,1351,1396,1442,1490,1539,1590,1643,1697,1754,1812,1872,1934,1998,2064,2133,2203,2277,2352,2430,2511,2594,2680,2769,2860,2955,3053,3154,3259,3367,3479,3594,3713,3836,3964,4095};

uint16_t weber_fechner(uint8_t i) {
	return pgm_get(weber_fechner_table[i],word);
}
